# Generated by Django 5.2.4 on 2025-07-10 14:21

import encrypted_model_fields.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descricao', encrypted_model_fields.fields.EncryptedTextField()),
                ('tipo', models.CharField(max_length=100)),
                ('envolvidos', encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='novo', max_length=30)),
                ('codigo_acomp', models.CharField(blank=True, max_length=12, null=True)),
            ],
        ),
    ]
